---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
data:
  AUTH_GRPC_PORT: "5005"
  JWT_EXPIRATION_TIME: "1m"
  REFRESH_TOKEN_EXPIRATION_TIME: "10d"
  LOG_RETENTION_DAYS: "7d"
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
type: Opaque
data:
  JWT_SECRET: "Njc3ZjM4ODJhN2E3ZWZjM2Q3MGI4OTZiOThjMTE1NDc0ZmE3YjBlNDRmMDdiMTgyODdkNWI2Yjg0ZjI3NjEwNGExNDE4MGFmMTUyOTNjZWNlMzQxN2M5YmU1NTkzMDFkNGZkYmU5MjU2YzJiMzdlNDkzMjRkMGZkNzBiYmIyNTk="
  REFRESH_TOKEN_SECRET: "Njc3ZjM4ODJhN2E3ZWZjM2Q3MGI4OTZiOThjMTE1NDc0ZmE3YjBlNDRmMDdiMTgyODdkNWI2Yjg0ZmExNDE4MGFmMTUyOTNjZWNlMzQxN2M5YmU1NTkzMDFkNGZkYmU5MjU2YzJiSkZJRFNKVklEWUdJRFdPMzgzOTU3MzY0ODM5Mg=="
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: auth-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5005
        envFrom:
        - configMapRef:
            name: auth-service-config
        - secretRef:
            name: auth-service-secrets
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  ports:
  - port: 5005
    targetPort: 5005
  selector:
    app: auth-service